#+TITLE: 出版物, 発表
#+AUTHOR: KAWAI Yuta
#+LANGUAGE: ja
#+OPTIONS: toc:nil num:nil author:nil creator:nil LateX:t
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="org.css">
#+HTML_HEAD: <style type="text/css">
#+HTML_HEAD:<!--/*--><![CDATA[/*><!--*/
#+HTML_HEAD: div.figure { float:left; }
#+HTML_HEAD: /*]]>*/-->
#+HTML_HEAD: </style>
#+MACRO: em @<font size=+1 color=red>$1@</font>
# #+HTML_HEAD_EXTRA: <style> .figure p {text-align: right;}</style>
# #+HTML_HEAD_EXTRA: <style type="text/css">div.org-src-container{border:1px solid green;width:50%;float:right;}</style>
# #+HTML_HEAD_EXTRA: <style type="text/css">div.figure { float:left; } </style>

[[./index.html][<Top ページに戻る>]]

* 原著論文

** 筆頭論文 
- _Yuta Kawai_, Hirofumi Tomita, 2023:  Numerical Accuracy Necessary for Large-Eddy Simulation of Planetary Boundary Layer Turbulence using Discontinuous Galerkin Method, Monthly Weather Review, 151, 6.
- _Yuta Kawai_ and Hirofumi Tomita, 2021: Numerical Accuracy of Advection Scheme necessary for Large-Eddy Simulation of Planetary Boundary Layer Turbulence, Monthly Weather Review, 149, 9.

** 共著論文
- Hiroaki Miura, Tamaki Suematsu, _Yuta Kawai_, Yoko Yamagami, Daisuke Takasuka, Yuki Takano, Ching-Shu Hung, Kazuya Yamazaki, Chihiro Kodama, Yoshiyuki Kajikawa, and Yukio Masumoto, 2023: Asymptotic matching between weather and climate models, Bulletin of the American Meteorological Society, 104, E2308-E2315. 
- Masaki Ishiwatari, Kensuke Nakajima, Shin-ichi Takehiro, Yoshi-Yuki Hayashi, _Yuta Kawai_, Yoshiyuki O. Takahashi, 2021: Revision of “Dependence of climate states of gray atmosphere on solar constant: From the runaway greenhouse to the snowball state" by Ishiwatari et al. (2007), Journal of Geophysical Research: Atmospheres, 126, e2019JD031761.
- Hisashi Yashiro, Koji Terasaki, _Yuta Kawai_, Shuhei Kudo, Takemasa Miyoshi, Toshiyuki Imamura, Kazuo Minami, Hikaru Inoue, Tatsuo Nishiki, Takayuki Saji, Masaki Satoh, Hirofumi Tomita, 2020: A 1024-member ensemble data assimilation with 3.5-km mesh global weather simulations.  In 2020 SC20: International Conference for High Performance Computing, Networking, Storage and Analysis (SC) (pp. 1-10). IEEE Computer Society.

** 投稿中の論文
- _Yuta Kawai_ and Hirofumi Tomita: Development of High-order Global Dynamical Core using Discontinuous Galerkin Method for atmospheric LES and proposal of test cases, submitted to GMD

** 投稿準備の論文
- _Yuta Kawai_, Yoshiyuki O. Takahashi, Masaki Ishiwatari, Kensuke Nakajima, Shin-ichi Takehiro, Hiroki Kashimura, Hirofumi Tomita, Yoshi-Yuki Hayashi: Solar constant dependence of climate states of an ocean planet with gray atmosphere: Effects of heat capacity and heat transport of the ocean, in preparation 


* 学会発表, 研究発表
** 2024 年度
- _河合佑太_, 富田浩文, 2024: 不連続ガラーキン法を用いた全球大気力学コアの開発: 乱流モデルの導入と検証実験, 日本地球惑星科学連合 2024 年大会, 2024 年 5 月 29 日 (講演番号 MGI29-08)
- _Kawai, Y._, Ren, X., Katagiri, T., Nishizawa, S., Tomita, H., 2024: Development of an atmospheric model using discontinuous Galerkin method: Evaluation of the computational performance on A64FX, 16th JLESC Workshop, 16th April, 2024

** 2023 年度
- 任軒正博, _河合佑太_, 富田浩文, 片桐孝洋, 西澤誠也, 星野哲也, 河合直聡, 永井亨, 2024: 不連続ガラーキン法を基づいた大気力学コアの性能評価と改善について. 第193回HPC研究会, 2024 年 3 月 18 日
- _Kawai, Y._, Tomita, H., 2024: Validation of a Global Nonhydrostatic Atmospheric Dynamical Core using Discontinuous Galerkin method, AMS 104th Annual Meeting, 30th January, 2024
- Xuanzhengbo Ren, _Yuta Kawai_, Hirofumi Tomita, Takahiro Katagiri, Seiya Nishizawa, Tetsuya Hoshino, Masatoshi Kawai, Toru Nagai, 2024: An Evaluation of Discontinuous Galerkin Method based Global Nonhydrostatic Atmospheric Dynamical Core on A64FX Platform, HPC Asia 2024, 26th January, 2024
- _河合佑太_, 任軒正博, 片桐孝洋, 富田浩文, 2024:不連続ガラーキン法に基づく流体計算コードの富岳における計算効率について, 富岳 NEXT FS 気象気候研究会, 2024 年 1 月 18 日
- _河合佑太_, 富田浩文, 2023: 不連続ガラーキン法を用いた全球大気力学コアの妥当性の検証, 日本気象学会 2023 年度秋季大会, 2023 年 10 月 24 日 (講演番号 C210)
- _河合佑太_, 富田浩文, 2023: 不連続 Galerkin 法に基づく全球力学コアのテスト計算, 第 9 回マッデン・ジュリアン振動研究会, 2023 年 9 月 29 日
- _河合佑太_, 富田浩文, 2023: 不連続ガラーキン法を用いた非静力学大気力学コアの開発: 地形の考慮, 日本地球惑星科学連合 2023 年大会, 2023 年 5 月 26 日 (講演番号 MGI30-03)
- _Kawai, Y._, Tomita, H., 2023: Development of a global atmospheric nonhydrostatic dynamical core using discontinuous Galerkin method, The 6th International Workshop on Nonhydrostatic Models (NHM-WS 2023), 31th August - 2nd September, 2023
- _河合佑太_, 富田浩文, 2023: 不連続ガラーキン法を用いた非静力学大気力学コアの開発: 地形の考慮, 日本地球惑星科学連合 2023 年大会, 2023 年 5 月 26 日 (講演番号 MGI30-03)
- _河合佑太_, 富田浩文, 2023: 地形を考慮した不連続ガラーキン法に基づく大気力学コアの開発, 日本気象学会 2023 年度春季大会, 2023 年 5 月 18 日 (講演番号 C301)
- _Kawai, Y._, Tomita, H., 2023: A study on discontinuous Galerkin method for atmospheric high-resolution simulations, Global Storm-Resolving Modeling Mini Workshop, 11-12th May, 2023

** 2022 年度
- _河合佑太_, 富田浩文, 2023: 不連続ガラーキン法を用いた大気力学コア SCALE-DG (仮), 富岳 NEXT FS 気象気候会合, 2023 年 1 月 19 日 
- _Kawai, Y._, Tomita, H., 2023: A study on Numerical Accuracy of Dynamical Core Necessary for Large-Eddy Simulation of Planetary Boundary Layer Turbulence, AMS 103rd Annual Meeting, 9th January, 2023
- _河合佑太_, 富田浩文, 2022: 不連続ガラーキン法を用いた大気モデルの開発: 湿潤過程の導入, 日本気象学会 2022 年度秋季大会, 2022 年 10 月 26 日 (講演番号 C303)
- _Kawai, Y._, Tomita, H., 2022: A development of an atmospheric model using the discontinuous Galerkin method: Inclusion of moist process, DNA 気候学 夏の勉強会, 2022 年 9 月 9 日 
- _河合佑太_, 富田浩文, 2022: 大気ラージエディシミュレーションにおける不連続ガラーキン法の数値誤差の影響に関する研究, 日本地球惑星科学連合 2022 年大会, 2022 年 5 月 23 日 (講演番号 MGI33-11)
- _河合佑太_, 富田浩文, 2022: 不連続ガラーキン法を用いた大気ラージエディシミュレーション: 数値誤差に関する指標の導出, 日本気象学会 2022 年度春季大会, 2022 年 5 月 18 日 (講演番号 BL-04+)
- _Kawai, Y._, Tomita, H., 2022: A study on discontinuous Galerkin method for future high-resolution atmospheric simulations, DNA Climate Science Meeting, 26th April, 2022


** 2021 年度
- _Kawai, Y._, Tomita, H., 2022: Investigation of numerical errors with the Discontinuous Galerkin method for atmospheric high-resolution simulations, The 4th R-CCS International Symposium, 7th February 2022 (Lightning talk and poster)
- Sueki,K., Kajikawa, Y., Adachi, S., Yamaura, T., _Kawai, Y._, Tomita H., and Oishi,S., 2022: High-resolution ensemble prediction experiment for extreme rainfall event in western Japan in July 2018 using Fugaku,  The 4th R-CCS International Symposium, 7th February 2022 (Lightning talk and poster)
- _河合佑太_, 末木健太, 富田浩文, 高解像度大気計算における力学スキームの離散精度の影響に関する研究, 2021: 日本気象学会 2021 年度秋季大会, 2021 年 12 月 8 日 (講演番号 SP5-11+, 招待講演)
- 八代 尚, 寺崎 康児,  中野 満寿男, 小玉 知央, _河合 佑太_, 富田 浩文, 2021: 計算機システムと気象・気候分野のアプリケーションのコデザイン：NICAM-LETKFの経験から, 日本気象学会 2021 年度秋季大会, 2021 年 12 月 8 日 (講演番号 SP5-13+, 招待講演)
- _河合佑太_, 高橋芳幸, 石渡正樹(発表者), 竹広真一, 中島健介, 樫村博基, 富田浩文, 林祥介, 2021: 大気吸収係数が海惑星の気候レジーム図に与える影響, 日本気象学会 2021 年度秋季大会, 2021 年 12 月 6 日 (講演番号 SP3-12+)
- _河合佑太_, 富田浩文, 2021: 不連続ガラーキン法を用いた全球大気力学コアの開発, 第 2 回雲解像気候学ワークショップ, 2021 年 9 月 22 日
- _Kawai, Y._, Sueki, K., Tomita, H., 2021: A study on the impact of advection schemes on convergence of convective updraft ensembles with respect to the grid spacing, The Fifth Convective-Permitting Modeling Workshop 2021, 10th September 2021, (poster presentation). 
- _河合佑太_, 富田浩文, 2021: 不連続ガラーキン法を用いた大気境界層乱流のラージエディシミュレーション, DNA 気候学 第一回挑戦的モデル班研究会, 2021 年 8 月 5 日
- _河合佑太_, 富田浩文, 2021: 不連続ガラーキン法を用いた大気境界層乱流のラージエディシミュレーション, 日本地球惑星科学連合 2021 年大会, 2021 年 6 月 4 日 (講演番号 MGI35-03)
- 八代 尚, 寺崎 康児, _河合 佑太_, 工藤 周平, 三好 建正, 今村 俊幸, 南 一生, 中野 満寿男, 小玉 知央, 佐藤 正樹, 富田 浩文, 2021: System-Application Co-design for Supercomputer Fugaku and Global Ensemble Weather Data Assimilation, 日本地球惑星科学連合 2021 年大会, 2021 年 6 月 4 日 (講演番号AAS07-P04)
- _河合佑太_, 富田浩文, 2021: 不連続ガラーキン法を用いた大気境界層乱流のラージエディシミュレーション, 日本気象学会 2021 年度春季大会, 2021 年 5 月 18 日 (講演番号 D1K)

** 2020 年度
- _河合佑太_, 富田浩文, 2021: 全球大気 LES に向けた力学コアの必要精度に関する研究, 第2回先端的データ同化と巨大アンサンブル手法に関する研究会, 2021 年 3 月 10 日
- _河合佑太_, 富田浩文, 2020: 大気境界層LESにおける高精度力学コアの必要性について, 第1回雲解像気候学ワークショップ, 2020 年 12 月 23 日
- _河合佑太_, 富田浩文, 2020: 全球LESに向けた力学コアの必要性度に関する研究, NICAM 開発者会議, 2020 年 12 月 1 日
- _河合佑太_, 富田浩文, 2020: ラージエディシミュレーションで必要とされる力学コアの離散精度に関する研究, 日本気象学会 2020 年度秋季大会, 2020 年 10 月 29 日 (講演番号 BL-01+)
- _河合佑太_, 富田浩文, 2020: ラージエディシミュレーションに必要とされる大気力学コアの数値精度に関する研究, 日本地球惑星科学連合 2020 年大会, 2020 年 7 月 14 日 (COVID-19 によりオンラインによる大会開催)
- _河合佑太_, 富田浩文, 2020: ラージエディシミュレーションにおける力学コアの高精度化の必要性に関する考察, 日本気象学会 2020 年度春季大会, 2020 年 5 月 22 日 (講演番号 C406) (COVID-19 により予稿集発行による大会開催)
- 八代尚, 寺崎康児, 中野満寿男, 小玉知央, _河合佑太_, 富田浩文, 2020: スーパーコンピュータ「富岳」開発における 気象・気候分野のアプリケーションコデザイン, 日本気象学会 2020 年度春季大会, 2020 年 5 月 22 日 (講演番号 A362) (COVID-19 により予稿集発行による大会開催)

** 2019 年度
- _河合佑太_, 高橋芳幸, 石渡正樹, 西澤誠也, 竹広真一, 中島健介, 富田浩文, 林祥介, 2019: 海惑星気候の太陽定数依存性の研究: 灰色大気の吸収係数が大きい場合における海洋熱輸送の影響, 日本地球惑星科学連合 2019 年大会, 2019 年 5 月 28 日, 幕張メッセ国際会議場 (講演番号 M-IS11)

** 2018 年度

- _河合佑太_, 高橋芳幸, 石渡正樹, 西澤誠也, 竹広真一, 中島健介, 富田浩文, 林祥介, 2018: 海惑星気候の太陽定数依存性に関する数値的研究: 海洋熱容量と海洋熱輸送の効果, 日本地球惑星科学連合 2018 年大会, 2018 年 5 月 22 日, 幕張メッセ国際会議場 (講演番号 M-IS18)
- _河合佑太_, 高橋芳幸, 石渡正樹, 西澤誠也, 竹広真一, 中島健介, 富田浩文, 林祥介, 2018: 海惑星気候の太陽定数増減実験: 海洋熱容量と海洋熱輸送の効果, 日本気象学会2018年度春季大会, 2018 年 5 月 18 日, つくば国際会議場 (講演番号 A302)

** 2017 年度


- _Kawai, Y._, Takahashi, Y. O., Ishiwatari, M., Nishizawa, S., Takehiro, S., Nakajima, K., Tomita, H., Hayashi, Y.-Y., 2018: A study on dependence of ocean planet climates on the solar constant: the effect of oceanic heat capacity and oceanic heat transport. CPS/WTK Mini-Workshop on Planetary Atmospheres II, 28th March 2018, CPS, Kobe University
- 石渡正樹, _河合佑太_, 松田幸樹, 高橋芳幸, 中島健介, はしもとじょーじ, 倉本 圭, 杉山耕一朗, 小高 正嗣, 林 祥介, 2018: 地球型系外惑星気候のモデリングと数値実験, 第19回惑星圏研究会, 2018 年 2 月 28 日, 東北大学
- _河合佑太_, 高橋芳幸, 石渡正樹, 西澤誠也, 竹広真一, 中島健介, 富田浩文, 林祥介, 2017: 全球海惑星の気候レジーム〜海洋大循環の効果〜, 日本気象学会2017年度秋季大会, 2017 年 10 月 30 日, 北海道大学 (講演番号 C164)
- _河合佑太_, 高橋芳幸, 石渡正樹, 西澤誠也, 竹広真一, 中島健介, 富田浩文, 林祥介, 2017: 全球海惑星気候の太陽定数増減依存性の研究: 海洋大循環の影響の検証, 地球電磁気・地球惑星圏学会 2017年度 秋季大会, 2017 年 10 月 18 日, 京都大学宇治キャンパス (講演番号 R009-12)
- _河合佑太_, 高橋芳幸, 石渡正樹, 西澤誠也, 竹広真一, 中島健介, 富田浩文, 林祥介, 2017: 大気海洋海氷結合モデルを用いた全球海惑星気候の太陽定数依存性に関する研究, 日本惑星科学会 2017 年秋季講演会, 2017 年 9 月 27 日, 大阪大学豊中キャンパス (講演番号 A6)
- _河合佑太_, 高橋芳幸, 石渡正樹, 西澤誠也, 竹広真一, 中島健介, 富田浩文, 林祥介, 2017: 大気海洋海氷結合モデルを用いた水惑星の気候に対する海洋大循環の影響の数値的研究, 日本地球惑星科学連合 2017 年大会, 2017 年 5 月 22 日, 幕張メッセ国際会議場 (講演番号 MGI32-P02)

** 2016 年度

- _Kawai, Y._, Takahashi, Y. O., Ishiwatari, M., Nishizawa, S., Takehiro, S., Nakajima, K., Tomita, H., Hayashi, Y.-Y., 2017: Development of a coupled model to explore aquaplanet climates and aquaplanet simulation with zonally symmetric dynamic ocean. WTK Aquaplanet Workshop, 24th January 2017, CPS, Kobe University
- _河合 佑太_, 高橋 芳幸, 石渡 正樹, 西澤 誠也, 竹広 真一, 中島 健介, 富田 浩文, 林 祥介, 2016: 大気海洋海氷結合モデルによる水惑星の気候の数値実験. 日本地球惑星科学連合 2016 年大会, 2016 年 5 月 24 日, 幕張メッセ国際会議場 (講演番号 MGI22-P10)
- _河合佑太_, 高橋芳幸, 石渡正樹, 西澤誠也, 竹広真一, 中島健介, 富田浩文, 林祥介 2016: 大気海洋海氷結合モデルによる水惑星の気候シミュレーション. 惑星大気研究会「水惑星」, 2016 年 3 月 9 日, 国立天文台三鷹

** 2015 年度

- _Kawai, Y._, Takahashi, Y. O., ishiwatari, M., Nishizawa, S., Takehiro, S., Nakajima, K., Tomita, H., Hayashi, Y.-Y., 2016: Development of a coupled atmosphere-ocean-seaice model to explore aquaplanet climates, International Workshop on "Exoplanets and Disks: Their Formation and Diversity III", 22nd February 2016, Hotel Nikko Yaeyama
- _Kawai, Y._, Takahashi, Y. O., Ishiwatari, M., Nishizawa, S., Takehiro, S., Nakajima, K., Tomita, H., Hayashi, Y.-Y., 2015: Development of ocean general circulation model to understand an aquaplanet climate and preliminary numerical experiment, RIKEN Summer School, Sep 4th 2015, Hotel Heritage, Shinrin-Koen, Japan.

** 2014 年度

- _河合佑太_, 2014: 惑星の気候状態の理解に向けた海洋モテル開発と予備的実験, 第 5 回サイエンスフロンティア研究発表会, 2014 年 10 月 25 日, 神戸大学


* その他
** 2020 年度
- Masaki Ishiwatari, Kensuke Nakajima, Shin-ichi Takehiro, _Yuta Kawai_, Yoshiyuki O. Takahashi, George L. Hashimoto, Youhei Sasaki, Yoshi-Yuki Hayashi, 2021: Numerical studies on the variety of climates of exoplanets using idealistic configurations, CGER’S SUPERCOMPUTER MONOGRAP REPORT Vol.27

** 2019 年度
- 石渡正樹, 中島健介, 林祥介, _河合佑太_: 系外惑星も含めた地球型惑星の気候多様性の関する数値実験:大きな赤道傾斜角をもつ惑星の気候. 国立環境研究所スーパーコンピ ュータ利用研究年報 平成 30 年度

** 2018 年度
- 石渡正樹, 中島健介, 林祥介, 荻原弘尭, _河合佑太_: 系外惑星も含めた地球型惑星の気候多様性に関する数値実験: 海陸分布が気候に及ぼす影響, 国立環境研究所スーパーコンピュータ利用研究年報 平成 29 年度, p.104--108 

  
